[workspace]
members = [
    "album",
    "musician",
]

[workspace.dependencies]
axum = "0.6.20"
async-graphql = "6.0.5"
async-graphql-axum = "6.0.5"
tokio = { version = "1.17.0", features = ["full"] }
tokio-util = "0.7.8"
tokio-stream = "0.1.14"
tower-service = "0.3"
async-trait = "0.1.73"
